---
title: "Homework1"
author: "Trevor Kapuvari"
date: "2023-09-25"
output: 
  html_document:
    toc: true
    toc_float: true
    code_folding: hide
    number_sections: yes
editor_options: 
  markdown: 
    wrap: 72
---

```{r setup clear environment,  include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
rm(list=ls())
```

```{r setup, include=FALSE}
RegD = read.csv("https://github.com/TrevorKap/MUSA5000/raw/main/HW1/Data/RegressionData.csv")
# we don't want scientific notation
options(scipen=999)

library(sf)
library(sp)
library(ggplot2)
library(viridis)
library(dplyr)
library(MASS)
library(DAAG)
library(corrr)
library(autoNumCaptions)
library(gridExtra)
library(stargazer)
library(autoNumCaptions)
devtools::install_github("kstagaman/autoNumCaptions")
# load custom functions from the book 
root.dir = "https://github.com/TrevorKap/MUSA5000/raw/main/HW1/Data"
#Test1_shp <- st_read("https://github.com/TrevorKap/MUSA5000/raw/main/HW1/Data/RegressionData.shp")
Reg_db <- st_read(file.path(root.dir,"RegressionData.dbf"))
Reg_shp <- st_read("C:/Users/Owner/Documents/GitHub/MUSA5000/HW1/Data/RegressionData.shp")
# Line 43 is local only idfk how to fix this. 
```

This is a change to make sure I am pushing correctly to the repository.

```{r Distribution Histograms}
#Dependent Variable
hist(RegD$MEDHVAL, main = "Distribution of Median House Value", xlab = "MEDHVAL", breaks = 50)

#Predictors
hist(RegD$PCTBACHMOR, main = "Distribution of Proportion of Residents in Block with at least a Bachelors", xlab = "PCTBACHMORE", breaks = 50)

hist(RegD$PCTVACANT, main = "Proportion of Vacant Housing Units", xlab = "PCTVACANT", breaks = 50)

hist(RegD$PCTSINGLES, main = "Percent of Housing Units that are 'detached single family houses'", xlab = "PCTSINGLE", breaks = 50)

hist(RegD$NBELPOV100, main = "Households declared to be in poverty", xlab = "NBELPOV100", breaks = 50)

hist(RegD$MEDHHINC, main = "Median Household Income", xlab = "MEDHHINC", breaks = 50)
```

```{r Means, and Standard Deviation}
#Means and Standard Deviation 
#Median House Value
mean(RegD$MEDHVAL)
sd(RegD$MEDHVAL)

#Percent Bachelors
mean(RegD$PCTBACHMOR)
sd(RegD$PCTBACHMOR)

#Percent Vacant
mean(RegD$PCTVACANT)
sd(RegD$PCTVACANT)

#Percent Single Detached 
mean(RegD$PCTSINGLES)
sd(RegD$PCTSINGLES)

#Households Below Poverty Line
mean(RegD$NBELPOV100)
sd(RegD$NBELPOV100)

#Median Household Income
mean(RegD$MEDHHINC)
sd(RegD$MEDHHINC)
```

```{r Log Variables}
filter(RegD, MEDHVAL == 0)
RegD$LN_MEDHVAL <- log(RegD$MEDHVAL)

RegD$LN_PCBACHMORE <- log(1+RegD$PCTBACHMOR)
RegD$LN_BELPOV100 <- log(1+RegD$NBELPOV100)
RegD$LN_PCTVACANT <- log(1+RegD$PCTVACANT)
RegD$LN_PCTSINGLES <- log(1+RegD$PCTSINGLES)
```

```{r Logirtihmic Histograms}
#make 50 bins again 
hist(RegD$LN_MEDHVAL, main = "Log of Distribution of Median House Value", xlab = "LN MEDHVAL", breaks = 50)

hist(RegD$LN_PCBACHMORE, main = "Log of Distribution of Proportion of Residents in Block with at least a Bachelors", xlab = "LN PCTBACHMOR", breaks = 50)

hist(RegD$LN_PCTVACANT, main = "Log of Proportion of Vacant Housing Units", xlab = "LN PCTVACANT", breaks = 50)

hist(RegD$LN_PCTSINGLES, main = "Log of Percent of Housing Units that are 'detached single family houses'", xlab = "LN PCTSINGLE", breaks = 50)

hist(RegD$LN_BELPOV100, main = "Log of Households declared to be in poverty", xlab = "LN NBELPOV100", breaks = 50)

```

```{r Correlation Matrix}
RegDnums <- 
  select_if(st_drop_geometry(Reg_shp), is.numeric) %>% na.omit()

RegDnums %>% 
  correlate() %>% 
  autoplot() +
  geom_text(aes(label = round(r,digits=2)), size = 3.5, order = "hclust", type = "upper", tl.cex = 3)



```

```{r Scatter Plots between Median Home Value & Predictors}
par(mfrow = c(2, 2))
plot(RegD$LN_MEDHVAL, RegD$PCBACHMOR, main = "LN_MEDHVAL vs. PCBACHMORE", xlab = "LN_MEDHVAL", ylab = "PCBACHMORE")

plot(RegD$LN_MEDHVAL, RegD$PCTVACANT, main = "LN_MEDHVAL vs. PCTVACANT", xlab = "LN_MEDHVAL", ylab = "PCTVACANT")

plot(RegD$LN_MEDHVAL, RegD$LN_BELPOV100, main = "LN_MEDHVAL vs. LN_BELPOV100", xlab = "LN_MEDHVAL", ylab = "LN_BELPOV100")

plot(RegD$LN_MEDHVAL, RegD$PCTSINGLES, main = "LN_MEDHVAL vs. PCTSINGLES", xlab = "LN_MEDHVAL", ylab = "PCTSINGLES")

```

```{r Pearson Correlations}
cor(RegD$LN_MEDHVAL, RegD$PCTVACANT)

cor(RegD$LN_MEDHVAL, RegD$PCTSINGLES)

cor(RegD$LN_MEDHVAL, RegD$PCTBACHMOR)

cor(RegD$LN_MEDHVAL, RegD$LN_BELPOV100)

```

```{r Chloropleth Maps}
par(mfrow = c(2, 2))
ggplot() +
  geom_sf(data = Reg_shp, aes(fill = LNMEDHVAL))+
#  coord_sf(projection = crs("C:/Users/Owner/Documents/RStudio/MUSAStatistics/Lecture1RegressionData/RegressionData.shp")
  labs(title = "Logarithmic Median Home Value")+
  scale_fill_gradient(low = "white", high = "red")+
  theme_bw()

ggplot() +
  geom_sf(data = Reg_shp, aes(fill = PCTVACANT))+
  labs(title = "Percent of Vacant Homes")+
  scale_fill_gradient(low = "white", high = "blue")+
  theme_bw()

ggplot() +
  geom_sf(data = Reg_shp, aes(fill = PCTSINGLES))+
  labs(title = "Percentage of Houses classified as Sinlge Family Detached")+
  scale_fill_gradient(low = "white", high = "brown")+
  theme_bw() 

ggplot() +
  geom_sf(data = Reg_shp, aes(fill = PCTBACHMOR))+
  labs(title = "Percentage of people with at least a Bachelors")+
  scale_fill_gradient(low = "white", high = "darkgreen")+
  theme_bw()

ggplot() +
  geom_sf(data = Reg_shp, aes(fill = LNNBELPOV))+
  labs(title = "Log of Households Below the Poverty Line")+
  scale_fill_gradient(low = "white", high = "purple")+
  theme_bw()


```

## Part 2

```{r regression part A}
Regression <- lm(LNMEDHVAL ~ PCTVACANT + PCTSINGLES + PCTBACHMOR + LNNBELPOV, data = Reg_shp)

summary(Regression)

```

```{r anova of regression Part B }
anova(Regression)
```

```{r Part C}

predictions <- fitted(Regression)

residuals <- residuals(Regression)

standardized_residuals <- rstandard(Regression)

```

```{r Part D}

plot(predictions, standardized_residuals,
    xlab = "Predicted Values",
    ylab = "Standardized Residuals",
    main = "Scatter Plot of Standardized Residuals vs. Predicted Values")
    abline(0, 0, lty = 2)
    title("Scatter Plot of Standardized Residuals vs. Predicted Values")
    
```

```{r Question 3}

MASS::stepAIC(Regression, direction="both")$anova

```

```{r Question 4, fig.width=5, fig.height=5}
 
cv_results <- DAAG::CVlm(data=as.data.frame(Reg_shp), Regression, m=5)
mse <- attr(cv_results, "ms")
rmse <- sqrt(mse)
rmse

```

```{r Question 4 set model}
hist(standardized_residuals)

minimum_standard_residuals <- min(standardized_residuals)
centered_standard_residuals <- standardized_residuals-minimum_standard_residuals

ggplot()+
  geom_sf(data=Reg_shp, aes(fill = centered_standard_residuals+1))+
  labs(title = "Centered Standard Residual")+
  scale_fill_gradient(low = "black", high = "orange")+
  theme_bw()

ggplot(data=Reg_shp)+geom_sf(fill=centered_standard_residuals+1)

#not sure which one to use

```