---
title: "Audience Targetting for Housing Subsidies"
author: "Trevor Kapuvari"
date: "October 13,2023"
output:
  html_document:
    toc: true
    toc_float: true
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message = FALSE, warning = FALSE)
```

# Motivation of the Analysis





```{r load_packages, warning = FALSE}
options(scipen=10000000)

library(tidyverse)
library(kableExtra)
library(caret)
library(knitr) 
library(pscl)
library(plotROC)
library(pROC)
library(jtools)
library(lubridate)
library(stargazer)



```

```{r load_data, cache = TRUE}
palette5 <- c("#981FAC","#CB0F8B","#FF006A","#FE4C35","#FE9900")
palette4 <- c("#981FAC","#FF006A","#FE4C35","#FE9900")
palette2 <- c("#981FAC","#FF006A")


housingsubsidy <- read.csv("https://github.com/urbanSpatial/Public-Policy-Analytics-Landing/raw/master/DATA/Chapter6/housingSubsidy.csv")


```

# Data Exploration

```{r exploratory_continuous}
  housingsubsidy %>%
    dplyr::select(y,unemploy_rate, mortgage, taxbill_in_phl, cons.price.idx, inflation_rate, cons.conf.idx) %>%
    gather(Variable, value, -y) %>%
      ggplot(aes(y, value, fill=y)) + 
        geom_bar(position = "dodge", stat = "summary", fun = "mean") + 
        facet_wrap(~Variable, scales = "free") +
        scale_fill_manual(values = palette2) +
        labs(x="Click", y="Value", 
             title = "This says fucking nothing",
             subtitle = "(continous outcomes)") +
        theme(legend.position = "none")
```

```{r exploratory_continuous_density, message = FALSE, warning = FALSE}
housingsubsidy %>%
    dplyr::select(y,unemploy_rate, mortgage, taxbill_in_phl, cons.price.idx, inflation_rate, cons.conf.idx) %>%
    gather(Variable, value, -y) %>%
    ggplot() + 
    geom_density(aes(value, color=y), fill = "transparent") + 
    facet_wrap(~Variable, scales = "free") +
    scale_fill_manual(values = palette2) +
    labs(title = "Feature distributions click vs. no click",
         subtitle = "(continous outcomes)")
```

```{r exploratory_binary, message = FALSE, warning = FALSE}
housingsubsidy %>%
    dplyr::select(y, month, poutcome, education) %>%
    gather(Variable, value, -y) %>%
    count(Variable, value, y) %>%
      ggplot(., aes(value, n, fill = y)) +   
        geom_bar(position = "dodge", stat="identity") +
        facet_wrap(~Variable, scales="free") +
        scale_fill_manual(values = palette2) +
        labs(x="Click", y="Value",
             title = "Feature associations with the likelihood of click",
             subtitle = "Categorical features") +
        theme(axis.text.x = element_text(angle = 45, hjust = 1))
```


```{r exploratory_continuous}
housingsubsidy %>%
  dplyr::select(age,previous, unemploy_rate, cons.price.idx, cons.conf.idx, inflation_rate, spent_on_repairs, y) %>%
  gather(variable, value, -y) %>%
  group_by(y, variable) %>% summarise(mean=mean(value)) %>%
ggplot(aes(x=y,y=mean,fill=y))+
  geom_bar(stat='identity')+
  facet_wrap(~variable,scales = "free")+
  labs(x="Enter Housing Subsity Program", y="Value", 
      title = "Feature associations with likelihood of entering housing subsidy program",
      subtitle = "Continous outcomes")
      
```

# Non Continuous Variables
```{r exploratory_non_continuous}

housingsubsidy %>%
  dplyr::select()

```



# Making Models

```{r Training and Test Set}
set.seed(3456)
trainIndex <- createDataPartition(housingsubsidy$y_numeric, p = .65,
                                  list = FALSE,
                                  times = 1)
HSTrain <- housingsubsidy[trainIndex,]
HSTest  <- housingsubsidy[-trainIndex,]

#Running the Model

HSModel <- glm(y_numeric ~ .,
                  data=HSTrain %>% 
                    dplyr::select(age,previous, unemploy_rate, cons.price.idx, cons.conf.idx, inflation_rate, spent_on_repairs, y_numeric),
                  family="binomial" (link="logit"))

summary(HSModel)


```

## Model 2

```{r second_model}
HSModel2 <- glm(y_numeric ~ .,
                  data=HSTrain %>% dplyr::select(age,previous, unemploy_rate, cons.price.idx, cons.conf.idx, inflation_rate, pdays,  spent_on_repairs, y_numeric),
                  family="binomial" (link="logit"))

summary(HSModel2)

```


```{r fit_metrics}

pR2(HSModel2)

```


```{r testProbs}

testProbs <- data.frame(Outcome = as.factor(HSTest$y_numeric),
                        Probs = predict(HSModel2, HSTest, type= "response"))
```

## Discussion 3

Look at the plot of our predicted probabilities for our observed clickers (`1`) and non-clickers (`0`). **Write a sentence or two about how you think our model is performing.**

```{r plot_testProbs}
ggplot(testProbs, aes(x = Probs, fill = as.factor(Outcome))) + 
  geom_density() +
  facet_grid(Outcome ~ .) +
  scale_fill_manual(values = palette2) +
  labs(x = "Joins", y = "Density of probabilities",
       title = "Distribution of predicted probabilities by observed outcome") +
  theme(strip.text.x = element_text(size = 18),
        legend.position = "none")
```